module: KNContacts
github_url: https://github.com/dragosrobertn/KNContacts
root_url: https://dragosrobertn.github.io/KNContacts
author: dragosrobertn
author_url: https://github.com/dragosrobertn
theme: fullwidth
clean: true
output: ./docs
documentation: ./*md
xcodebuild_arguments: [-scheme, 'KNContacts']
