os: osx
language: swift
cache: cocoapods
osx_image: xcode11.3

jobs:  
  include:
    - stage: "Tests"               
      name: "Unit Tests"
      script: xcodebuild clean build test -scheme KNContacts -destination 'platform=iOS Simulator,OS=12.4,name=iPhone 8' -testPlan KNContactsTestPlan | xcpretty

after_success:
  - gem install jazzy -v 0.13.1
  - make documentation
  - bash <(curl -s https://codecov.io/bash) -J 'KNContacts'

deploy:
  provider: pages
  cleanup: false
  keep_history: true
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
