os: osx
language: swift
cache: cocoapods
osx_image: xcode10.2

jobs:  
  include:
    - stage: "Tests"               
      name: "Unit Tests"
      script: xcodebuild -project KNContacts.xcodeproj -scheme KNContacts  -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' clean build test -only-testing:KNContactsTests | xcpretty
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: docs
        on:
          branch: master
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'KNContacts'
        - gem install jazzy
        - make documentation