os: osx
language: swift
cache: cocoapods
osx_image: xcode11.3

jobs:  
  include:
    - stage: "Tests"               
      name: "Unit Tests"
      script: xcodebuild -project KNContacts.xcodeproj -scheme KNContacts  -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11' clean build test -only-testing:KNContactsTests | xcpretty

after_success:
  - gem install jazzy -v 0.13.2
  - make documentation
  - bash <(curl -s https://codecov.io/bash) -J 'KNContacts'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs
  on:
    branch: master
